name: EabcMabcA

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'  # every 5 min UTC

jobs:
  run-algo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # ===== Cache Python dependencies =====
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run algo script
        env:
          FYERS_TOKEN: ${{ secrets.FYERS_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          mkdir -p logs
          python EabcMabcA.py | tee logs/run-$(date +'%Y-%m-%d-%H-%M-%S').txt

      # ===== Upload logs as artifact =====
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: algo-logs
          path: logs/
          retention-days: 7   # keep logs for 7 days (you can change)
