name: EabcMabcA

on:
  workflow_dispatch:

jobs:
  run-algo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run algo script and manage logs
        env:
          FYERS_TOKEN: ${{ secrets.FYERS_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          mkdir -p logs

          CURRENT_LOG="logs/current_run.log"
          FULL_HISTORY_LOG="logs/full_history.log"

          echo "===== RUN STARTED: $(date) =====" | tee -a "$CURRENT_LOG" "$FULL_HISTORY_LOG"

          # Run Python script and capture all output
          python EabcMabcA.py 2>&1 | tee -a "$CURRENT_LOG" "$FULL_HISTORY_LOG"

          echo "===== RUN FINISHED: $(date) =====" | tee -a "$CURRENT_LOG" "$FULL_HISTORY_LOG"

          # Keep only last 1000 runs in full_history.log
          awk 'BEGIN{RS="===== RUN STARTED:"; ORS=""} NR>1{runs[NR]=$0} END{start=NR-1000>1?NR-1000:1; for(i=start;i<=NR;i++) print "===== RUN STARTED:" runs[i]}' "$FULL_HISTORY_LOG" > "$FULL_HISTORY_LOG.tmp" && mv "$FULL_HISTORY_LOG.tmp" "$FULL_HISTORY_LOG"

          # Display only errors/warnings at the top for quick view
          echo "===== ERRORS / WARNINGS (highlighted) ====="
          grep -E "\[ERROR\]|\[WARNING\]" "$CURRENT_LOG" | sed \
              -e "s/\[ERROR\]/\x1b[31m[ERROR]\x1b[0m/g" \
              -e "s/\[WARNING\]/\x1b[33m[WARNING]\x1b[0m/g"

          # Display full current run log below
          echo "===== FULL CURRENT RUN LOG ====="
          sed -e "s/\[ERROR\]/\x1b[31m[ERROR]\x1b[0m/g" \
              -e "s/\[WARNING\]/\x1b[33m[WARNING]\x1b[0m/g" "$CURRENT_LOG"

      - name: Upload full history log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: full-history-log
          path: logs/full_history.log
          retention-days: 7
