name: EabcMabcA

on:
  workflow_dispatch:

jobs:
  run-algo:
    runs-on: ubuntu-latest
    steps:
      # -----------------------------
      # 1. Checkout repo
      # -----------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # -----------------------------
      # 2. Set up Python
      # -----------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # -----------------------------
      # 3. Cache pip
      # -----------------------------
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # -----------------------------
      # 4. Install dependencies
      # -----------------------------
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # -----------------------------
      # 5. Run algo script and manage logs
      # -----------------------------
      - name: Run algo script and manage logs
  env:
    FYERS_TOKEN: ${{ secrets.FYERS_TOKEN }}
    TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
    TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
    TRADE_CONFIGS: ${{ vars.TRADE_CONFIGS }}   # <-- NEW
  run: |
    mkdir -p logs
    CURRENT_LOG="logs/current_run.log"

          # IST timestamp
          IST_TIME=$(TZ="Asia/Kolkata" date +"%Y-%m-%d %I:%M:%S %p IST / %H:%M:%S 24h")

          # Log start
          echo -e "\033[1;34m===== RUN STARTED: $IST_TIME =====\033[0m" | tee -a "$CURRENT_LOG"

          # Run Python script
          python EabcMabcA.py 2>&1 | tee -a "$CURRENT_LOG"

          # Log finish
          IST_TIME_END=$(TZ="Asia/Kolkata" date +"%Y-%m-%d %I:%M:%S %p IST / %H:%M:%S 24h")
          echo -e "\033[1;34m===== RUN FINISHED: $IST_TIME_END =====\033[0m" | tee -a "$CURRENT_LOG"

          # Highlight errors/warnings
          echo -e "\033[1;34m===== ERRORS / WARNINGS (highlighted) =====\033[0m"
          grep -E "\[ERROR\]|\[WARNING\]" "$CURRENT_LOG" | sed \
              -e "s/\[ERROR\]/\x1b[31m[ERROR]\x1b[0m/g" \
              -e "s/\[WARNING\]/\x1b[33m[WARNING]\x1b[0m/g"

          # Full current run log (without yellow background)
          echo -e "\033[1;34m===== FULL CURRENT RUN LOG =====\033[0m"
          sed -e "s/\[ERROR\]/\x1b[31m[ERROR]\x1b[0m/g" \
              -e "s/\[WARNING\]/\x1b[33m[WARNING]\x1b[0m/g" \
              "$CURRENT_LOG"
