name: EabcMabcA

on:
  schedule:
    # Runs every 5 min from 9:00 AM IST to 11:30 PM IST
    - cron: '30-59/5 3-17 * * *'   # 9:00–23:00 IST
    - cron: '0-30/5 18 * * *'      # last half hour 23:00–23:30 IST
  workflow_dispatch:  # allows manual run

jobs:
  run-algo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run algo script
        env:
          FYERS_TOKEN: ${{ secrets.FYERS_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python EabcMabcA.py
