name: EabcMabcA

on:
  workflow_dispatch:

jobs:
  run-algo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run algo script (capture logs)
        env:
          FYERS_TOKEN: ${{ secrets.FYERS_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          mkdir -p logs
          python EabcMabcA.py 2>&1 | tee logs/run-$(date +'%Y-%m-%d_%H-%M-%S').txt

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: run-logs
          path: logs/
          retention-days: 7
